/*
 * Paygate API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Offset struct for Offset
type Offset struct {
	// ABA routing number
	RoutingNumber string `json:"routingNumber,omitempty"`
	// Account number used to offset records
	AccountNumber string `json:"accountNumber,omitempty"`
	// Account type used in offset record
	AccountType string `json:"accountType,omitempty"`
	// Memo for Offset EntryDetail record
	Description string `json:"description,omitempty"`
}
