/*
 * Paygate API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PpdDetail struct for PpdDetail
type PpdDetail struct {
	// Metadata for the transaction, placed in addenda 05 record
	PaymentInformation string `json:"paymentInformation,omitempty"`
}
