/*
 * Paygate API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Addenda02 struct for Addenda02
type Addenda02 struct {
	// Client defined string used as a reference to this record.
	Id string `json:"id,omitempty"`
	// 02 - NACHA regulations
	TypeCode string `json:"typeCode,omitempty"`
	// ReferenceInformationOne may be used for additional reference numbers, identification numbers, or codes that the merchant needs to identify the particular transaction or customer.
	ReferenceInformationOne string `json:"referenceInformationOne,omitempty"`
	// ReferenceInformationTwo  may be used for additional reference numbers, identification numbers, or codes that the merchant needs to identify the particular transaction or customer.
	ReferenceInformationTwo string `json:"referenceInformationTwo,omitempty"`
	// TerminalIdentificationCode identifies an Electronic terminal with a unique code that allows a terminal owner and/or switching network to identify the terminal at which an Entry originated.
	TerminalIdentificationCode string `json:"terminalIdentificationCode,omitempty"`
	// TransactionSerialNumber is assigned by the terminal at the time the transaction is originated.  The number, with the Terminal Identification Code, serves as an audit trail for the transaction and is usually assigned in ascending sequence.
	TransactionSerialNumber string `json:"transactionSerialNumber,omitempty"`
	// MMDD formatted timestamp identifies the date on which the transaction occurred.
	TransactionDate string `json:"transactionDate,omitempty"`
	// Indicates the code that a card authorization center has furnished to the merchant.
	AuthorizationCodeOrExpireDate string `json:"authorizationCodeOrExpireDate,omitempty"`
	// Identifies the specific location of a terminal (i.e., street names of an intersection, address, etc.) in accordance with the requirements of Regulation E.
	TerminalLocation string `json:"terminalLocation,omitempty"`
	// Identifies the city in which the electronic terminal is located.
	TerminalCity string `json:"terminalCity,omitempty"`
	// Identifies the state in which the electronic terminal is located
	TerminalState string `json:"terminalState,omitempty"`
	// Entry Detail Trace Number
	TraceNumber string `json:"traceNumber,omitempty"`
}
