/*
 * Paygate API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IatDetail struct {
	// Name of originating entity
	OriginatorName string `json:"originatorName,omitempty"`
	// Address of originating entity
	OriginatorAddress string `json:"originatorAddress,omitempty"`
	// City of originating entity
	OriginatorCity string `json:"originatorCity,omitempty"`
	// State of originating entity
	OriginatorState string `json:"originatorState,omitempty"`
	// Postal code of originating entity
	OriginatorPostalCode string `json:"originatorPostalCode,omitempty"`
	// ISO 3166 Country code of originating entity
	OriginatorCountryCode string `json:"originatorCountryCode,omitempty"`
	// Name of originating financial institution
	ODFIName string `json:"ODFIName,omitempty"`
	// ID qualifier number of originating FI
	ODFIIDNumberQualifier string `json:"ODFIIDNumberQualifier,omitempty"`
	// Identification of originating FI
	ODFIIdentification string `json:"ODFIIdentification,omitempty"`
	// ISO 4217 currency code of originating entity
	ODFIBranchCurrencyCode string `json:"ODFIBranchCurrencyCode,omitempty"`
	// Name of receiving entity
	ReceiverName string `json:"receiverName,omitempty"`
	// Address of originating entity
	ReceiverAddress string `json:"receiverAddress,omitempty"`
	// City of originating entity
	ReceiverCity string `json:"receiverCity,omitempty"`
	// State of originating entity
	ReceiverState string `json:"receiverState,omitempty"`
	// Postal code of originating entity
	ReceiverPostalCode string `json:"receiverPostalCode,omitempty"`
	// ISO 3166 country code of originating entity
	ReceiverCountryCode string `json:"receiverCountryCode,omitempty"`
	// Name of receiving financial institution
	RDFIName string `json:"RDFIName,omitempty"`
	// ID qualifier number of originating FI
	RDFIIDNumberQualifier string `json:"RDFIIDNumberQualifier,omitempty"`
	// Identification of receiving financial institution
	RDFIIdentification string `json:"RDFIIdentification,omitempty"`
	// ISO 4217 currency code of receiving entity
	RDFIBranchCurrencyCode string `json:"RDFIBranchCurrencyCode,omitempty"`
	// Name of foreign bank used in IAT transfer
	ForeignCorrespondentBankName string `json:"foreignCorrespondentBankName,omitempty"`
	// ID qualifier of foreign bank used
	ForeignCorrespondentBankIDNumberQualifier string `json:"foreignCorrespondentBankIDNumberQualifier,omitempty"`
	// ID number of foreign bank used
	ForeignCorrespondentBankIDNumber string `json:"foreignCorrespondentBankIDNumber,omitempty"`
	// ISO 3166 country code of foreign bank used
	ForeignCorrespondentBankBranchCountryCode string `json:"foreignCorrespondentBankBranchCountryCode,omitempty"`
}
