/*
 * Paygate API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TelDetail struct {
	// Phone number for optional communication during business hours required for TEL transfers
	PhoneNumber string `json:"phoneNumber,omitempty"`
	// Defines if the transfer is authorized for a single transaction or reoccurring
	PaymentType string `json:"paymentType,omitempty"`
}
