/*
 * Paygate API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CreateDepository struct for CreateDepository
type CreateDepository struct {
	// Legal name of the financial institution.
	BankName string `json:"bankName"`
	// Legal holder name on the account
	Holder string `json:"holder"`
	// Defines the type of entity of the account holder as an *individual* or *company*
	HolderType string `json:"holderType"`
	// Defines the account as *checking* or *savings*
	Type string `json:"type"`
	// The ABA routing transit number for the depository account.
	RoutingNumber string `json:"routingNumber"`
	// The account number for the depository account
	AccountNumber string `json:"accountNumber"`
	// Additional meta data to be used for display only
	Metadata string `json:"metadata,omitempty"`
}
