/*
 * Paygate API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Address optional object required for Know Your Customer (KYC) validation of this Originator
type Address struct {
	// first line of a postal address
	Address1 string `json:"address1,omitempty"`
	// second and optional line of a postal address
	Address2 string `json:"address2,omitempty"`
	// name of a United States incorporated city
	City string `json:"city,omitempty"`
	// two charcer code of a US state
	State string `json:"state,omitempty"`
	// United States postal code
	PostalCode string `json:"postalCode,omitempty"`
}
