/*
 * Paygate API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Addenda14 struct for Addenda14
type Addenda14 struct {
	// Client defined string used as a reference to this record.
	Id string `json:"id,omitempty"`
	// 10 - NACHA regulations
	TypeCode string `json:"typeCode,omitempty"`
	// Name of the Receiver bank
	RDFIName string `json:"RDFIName,omitempty"`
	// Receiving DFI Identification Number Qualifier The 2-digit code that identifies the numbering scheme used in the Receiving DFI Identification Number field 01 = National Clearing System 02 = BIC Code 03 = IBAN Code
	RDFIIDNumberQualifier string `json:"RDFIIDNumberQualifier,omitempty"`
	// This field contains the bank identification number of the DFI at which the Receiver maintains his account.
	RDFIIdentification string `json:"RDFIIdentification,omitempty"`
	// Receiving DFI Branch Country Code USb\" = United States (\"b\" indicates a blank space) This 3 position field contains a 2-character code as approved by the International Organization for Standardization (ISO) used to identify the country in which the branch of the bank that receives the entry is located. Values for other countries can be found on the International Organization for Standardization website: www.iso.org
	RDFIBranchCountryCode string `json:"RDFIBranchCountryCode,omitempty"`
	// EntryDetailSequenceNumber contains the ascending sequence number section of the Entry Detail or Corporate Entry Detail Record's trace number This number is the same as the last seven digits of the trace number of the related Entry Detail Record or Corporate Entry Detail Record.
	EntryDetailSequenceNumber float32 `json:"entryDetailSequenceNumber,omitempty"`
}
