# Step one: build scapresults
FROM registry.access.redhat.com/ubi8/go-toolset as builder
COPY . .
RUN make build
ARG VERSION=unknown
LABEL maintainer="Moov <support@moov.io>"
LABEL name="paygate"
LABEL version=$VERSION

FROM registry.access.redhat.com/ubi8/ubi-minimal
LABEL maintainer="Moov <support@moov.io>"
COPY --from=builder /opt/app-root/src/bin/paygate /bin/paygate
ENTRYPOINT ["/bin/paygate"]
