# TODO amount fields now take a currency code. USD default
#  - Look at https://godoc.org/golang.org/x/text/currency

# TODO GET endpoints should use the OAS 3 Link Object specification
#  - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#linkObject

# TODO Transfers objects now have an estimated ?posting? date
# TODO add Documents allowing Customer ID(passport, drivers license, idCard) to be uploaded and verified
# TODO Webhooks have been documented for retrieving events
# TODO add support for retrieving 1099-k for Originators

# Property names must conform to the following guidelines:
# - Resources are plural nouns /customers/
# - Property names should be meaningful names with defined semantics.
# - Property names must be camel-cased, ASCII strings.
# - The first character must be a letter, an underscore (_) or a dollar sign ($).
# - Subsequent characters can be a letter, a digit, an underscore, or a dollar sign.
# - Reserved JavaScript keywords should be avoided

openapi: "3.0.0"
info:
  description: |
    Moov ACH is a RESTful API enabling ACH transactions to be submitted and received without a deep understanding of a full NACHA file specification.

    An *Originator* can initiate a *Transfer* as either a push (credit) or pull (debit) to a *Customer*. Originators and Customers must have a valid *Depository* account for a Transfer. A *Transfer* is initiated by an Originator to a Customer with an amount and flow of funds.

    The Moov API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer). Our API has predictable, resource-oriented URLs, and uses HTTP response codes to indicate API errors. We use built-in HTTP features, like HTTP authentication and HTTP verbs, which are understood by off-the-shelf HTTP clients. We support [cross-origin resource sharing](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing), allowing you to interact securely with our API from client-side[...]

    Authorization the client credentials (2-legged) flow

    When an API requires a token generated using 2-legged OAuth, no end user is involved. You generate the token by passing your client credentials (Client Id and Client Secret) in a simple call to Create access token (/oauth2/token). The operation returns a token that’s good for about two weeks; when it expires, you just repeat the call and get a new token.

  version: "0.0.1"
  title: "Moov ACH"
  contact:
    email: "apiteam@moov.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: https://api.moov.io/v1/
    description: Production server
  - url: https://sandbox.moov.io/v1/
    description: Development server.
tags:
- name: Originators
  description: Originator objects are an organization or person that initiates an ACH Transfer to a Customer account either as a debit or credit. The API allows you to create, delete, and update your originators. You can retrieve individual originators as well as a list of all your originators. (Batch Header)
- name: Customers
  description: Customer objects are an individual or business used to perform transfer's with an originator and track multiple transactions associated with the customer. The API allows you to create, delete, and update your customers. You can retrieve individual customers as well as a list of all your customers. (Entry Detail)
- name: Depositories
  description: Depository objects represent a US bank or credit union that funds can be debited or credit from a transfer. A Depository must be associated with a customer or an originator. The API allows you to create, delete, and update your depositories. You can retrieve individual depositories as well as a list of all your depositories.
- name: Transfers
  description: Transfer objects create a transaction initiated by an originator to a customer with a defined flow and fund amount. The API allows you to create or delete a transfers while the status of the transfer is pending.
- name: Events
  description: Event objects are a notification of a state change of a resource. When an Event is created any active webhooks will be notified.
- name: Gateways
  description: Gateway objects identify the origin (sending point) and destination (receiving point) of the entries to be transferred. (File Header)
paths:
#ORIGINATORS
  /originators:
    get:
      tags:
      - Originators
      summary: Gets a list of Originators
      operationId: getOriginators
      security:
        - todo: [todo]
    post:
      tags:
      - Originators
      summary: Create a new Originator object
      operationId: addOriginator
      security:
        - oAuthSample: [admin]
  /originators/{originatorId}:
    get:
      tags:
      - Originators
      summary: Retrieves the details of an existing Originator. You need only supply the unique Originator identifier that was returned upon customer creation.
      operationId: getOriginatorByID
      security:
        - todo: [todo]
    patch:
      tags:
      - Originators
      summary: Updates the specified Originator by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
      operationId: updateOriginator
      security:
        - todo: [todo]
    delete:
      tags:
      - Originators
      summary: Permanently deletes an Originator and associated Customers, Depositories, and Transfers. It cannot be undone. Also immediately cancels any active Transfers for the Originator.
      security:
        - todo: [todo]
# CUSTOMERS
  /customers:
    get:
      tags:
      - Customers
      summary: Gets a list of Customers
      operationId: getCustomers
      security:
        - todo: [todo]
    post:
      tags:
      - Customers
      summary: Create a new Customer object
      operationId: addCustomers
      security:
        - todo: [todo]
  /customers/{customerId}:
    get:
      tags:
      - Customers
      summary: Get a Customer by ID
      operationId: getCustomerByID
      security:
        - todo: [todo]
    patch:
      tags:
      - Customers
      summary: Updates the specified Customer by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
      operationId: updateCustomer
      security:
        - todo: [todo]
    delete:
      tags:
        - Customers
      summary: Permanently deletes a customer and associated depositories and transfers. It cannot be undone. Immediately cancels any active Transfers for the customer.
      security:
        - todo: [todo]
  /customers/{customerId}/depositories:
    get:
      tags:
      - Customers
      summary: Get a list of Depository accounts for a Customer
      operationId: getDepositoriesByCustomerID
      security:
        - todo: [todo]
  /customers/{customerId}/depositories/{depositoryId}:
    get:
      tags:
      - Customers
      summary: Get a Depository accounts for a Customer based on it's ID
      operationId: getDepositoriesByID
      security:
        - todo: [todo]
  # DEPOSITORIES
  /depositories:
    get:
      tags:
      - Depositories
      summary: A list of all Depository objects for the authentication context.
      operationId: getDepositories
      security:
        - todo: [todo]
    post:
      tags:
      - Depositories
      summary: Create a new depository account for a Customer ID or Originator ID defined in the Parent parameter
      operationId: addDepository
      security:
        - todo: [todo]
  /depositories/{depositoryId}:
    get:
      tags:
      - Depositories
      summary: Get a Depository object for the supplied ID
      operationId: getDepositoryByID
      security:
        - todo: [todo]
    patch:
      tags:
      - Depositories
      summary: Updates the specified Depository by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
      operationId: updateDepository
      security:
        - todo: [todo]
    delete:
      tags:
      - Depositories
      summary: Permanently deletes a depository and associated transfers. It cannot be undone. Immediately cancels any active Transfers for the depository.
      security:
        - todo: [todo]
  /depositories/{depositoryId}/micro-deposits:
    post:
      tags:
      - Depositories
      summary: Initiates micro deposits to be sent to the Depository institution for account validation
      operationId: createMicroDeposits
      security:
        - todo: [todo]
# TRANSFERS
  /transfers:
    get:
      tags:
      - Transfers
      summary: A list of all Transfer objects
      operationId: getTransfers
      security:
        - todo: [todo]
    post:
      tags:
      - Transfers
      summary: Create a new transfer between an Originator and a Customer. Transfers cannot be modified. Instead delete the old and create a new transfer.
      operationId: addTransfer
      security:
        - oAuthSample: [transfers]
  /transfers/batch:
    post:
      tags:
        - Transfers
      summary: Create a new list of transfer, validate, build, and process. Transfers cannot be modified.
      operationId: addTransfers
      security:
        - oAuthSample: [transfers]
  /transfers/{transferId}:
    get:
      tags:
      - Transfers
      summary: Get a Transfer object for the supplied ID
      operationId: getTransferByID
      security:
        - oAuthSample: [transfers]
    delete:
      tags:
      - Transfers
      summary: It is possible to recall (delete) a transfer before it has been released from the financial institution.
      operationId: deleteTransferByID
      security:
        - oAuthSample: [transfers]
  /transfers/{transferId}/failed:
    post:
      tags:
        - Transfers
      summary: Get the NACHA return code and description
      operationId: getTransferNachaCode
      security:
        - oAuthSample: [transfers]
  /transfers/{transferId}/files:
    post:
      tags:
        - Transfers
      summary: Get the ACH files to be used in this transfer.
      operationId: getTransferFiles
      security:
        - oAuthSample: [transfers]
  /transfers/{transferId}/events:
    get:
      tags:
      - Transfers
      summary: Get all Events associated with the Transfer object's for the supplied ID
      operationId: getTransferByID
      security:
        - todo: [todo]
# EVENTS
  /events:
    get:
      tags:
      - Events
      summary: Gets a list of Events
      operationId: getEvents
      security:
        - todo: [todo]
  /events/{eventId}:
    get:
      tags:
      - Events
      summary: Get a Event by ID
      operationId: getEventByID
      security:
        - todo: [todo]
# Gateway
  /gateways:
    get:
      tags:
        - Gateways
      summary: Gets a list of Gatways
      operationId: getGateways
      security:
        - todo: [todo]
    post:
      tags:
      - Gateways
      summary: Create a new Gateway object
      operationId: addGateway
      security:
        - todo: [todo]
# WEBHOOK callback subscription
# TODO implement webhooks https://swagger.io/docs/specification/callbacks/

# Health and liveness probes
  /ping:
    get:
      tags:
      - Monitor
      summary: Check that the service is running
# COMPONENTS to be re-used
components:
  securitySchemes:
    todo:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.moov.io/docs/auth)
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/authorize
          tokenUrl: /oauth2/token
          scopes:
            todo: (Admin) Full access to all create, update, view, and delete all resources.
            # TODO(adam): oauth2 scopes, i.e.
            # 'read:transfers': Read existing Transfer objects
            # 'write:transfers': Create new Transfers
