/*
 * Paygate Admin API
 *
 * Paygate is ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// FileTransferConfig struct for FileTransferConfig
type FileTransferConfig struct {
	// Filepath for inbound files
	InboundPath string `json:"inboundPath,omitempty"`
	// Filepath for outbound files
	OutboundPath string `json:"outboundPath,omitempty"`
	// Filepath for return files
	ReturnPath string `json:"returnPath,omitempty"`
	// Go template for uploaded ACH filenames. Refer to our documentation on filename templates for more details. https://docs.moov.io/paygate/ach/#filename-templates
	OutboundFilenameTemplate string `json:"outboundFilenameTemplate,omitempty"`
}
