/*
 * Paygate Admin API
 *
 * Paygate is ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// FtpConfig struct for FtpConfig
type FtpConfig struct {
	// DNS or IP address for FTP server
	Hostname string `json:"hostname"`
	// username for authentication
	Username string `json:"username"`
	// password for authentication
	Password string `json:"password,omitempty"`
}
