/*
 * Paygate Admin API
 *
 * Paygate is ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UpdateDepository struct for UpdateDepository
type UpdateDepository struct {
	// Defines the status of the Depository account
	Status string `json:"status,omitempty"`
}
