/*
 * Paygate Admin API
 *
 * Paygate is ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

// MicroDepositAmount A string with currency code and amount
type MicroDepositAmount struct {
	Amount string `json:"amount,omitempty"`
}
