/*
 * Paygate Admin API
 *
 * Paygate is ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Features struct for Features
type Features struct {
	// HTTP calls to Moov Accounts service are disabled
	AccountsCallsDisabled bool `json:"accountsCallsDisabled,omitempty"`
	// HTTP calls to Moov Customers service are disabled
	CustomersCallsDisabled bool `json:"customersCallsDisabled,omitempty"`
}
