/*
 * Paygate Admin API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

// Addenda15 struct for Addenda15
type Addenda15 struct {
	// Client defined string used as a reference to this record.
	Id string `json:"id,omitempty"`
	// 10 - NACHA regulations
	TypeCode string `json:"typeCode,omitempty"`
	// Receiver Identification Number contains the accounting number by which the Originator is known to the Receiver for descriptive purposes. NACHA Rules recommend but do not require the RDFI to print the contents of this field on the receiver's statement.
	ReceiverIDNumber string `json:"receiverIDNumber,omitempty"`
	// Receiver's physical address
	ReceiverStreetAddress string `json:"receiverStreetAddress,omitempty"`
	// EntryDetailSequenceNumber contains the ascending sequence number section of the Entry Detail or Corporate Entry Detail Record's trace number This number is the same as the last seven digits of the trace number of the related Entry Detail Record or Corporate Entry Detail Record.
	EntryDetailSequenceNumber float32 `json:"entryDetailSequenceNumber,omitempty"`
}
