/*
 * Paygate Admin API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

// MergedFileHeader struct for MergedFileHeader
type MergedFileHeader struct {
	Origin          string `json:"origin,omitempty"`
	OriginName      string `json:"originName,omitempty"`
	Destination     string `json:"destination,omitempty"`
	DestinationName string `json:"destinationName,omitempty"`
}
