/*
 * Paygate Admin API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

// Features struct for Features
type Features struct {
	// HTTP calls to Moov Accounts service are disabled
	AccountsCallsDisabled bool `json:"accountsCallsDisabled,omitempty"`
	// HTTP calls to Moov Customers service are disabled
	CustomersCallsDisabled bool `json:"customersCallsDisabled,omitempty"`
}
