/*
 * Paygate Admin API
 *
 * Paygate is a RESTful API enabling Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transactions to be submitted and received without a deep understanding of a full NACHA file specification.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

// Addenda98 struct for Addenda98
type Addenda98 struct {
	// Client defined string used as a reference to this record.
	Id string `json:"id,omitempty"`
	// 98 - NACHA regulations
	TypeCode string `json:"typeCode,omitempty"`
	// ChangeCode field contains a standard code used by an ACH Operator or RDFI to describe the reason for a change Entry.
	ChangeCode string `json:"changeCode,omitempty"`
	// OriginalTrace This field contains the Trace Number as originally included on the forward Entry or Prenotification. The RDFI must include the Original Entry Trace Number in the Addenda Record of an Entry being returned to an ODFI, in the Addenda Record of an 98, within an Acknowledgment Entry, or with an RDFI request for a copy of an authorization.
	OriginalTrace string `json:"originalTrace,omitempty"`
	// The Receiving DFI Identification (addenda.RDFIIdentification) as originally included on the forward Entry or Prenotification that the RDFI is returning or correcting.
	OriginalDFI string `json:"originalDFI,omitempty"`
	// Correct field value of what ChangeCode references
	CorrectedData string `json:"correctedData,omitempty"`
	// Entry Detail Trace Number
	TraceNumber string `json:"traceNumber,omitempty"`
}
