/*
 * Paygate API
 *
 * PayGate is a RESTful API enabling first-party Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transfers to be created without a deep understanding of a full NACHA file specification. First-party transfers initiate at an Originating Depository Financial Institution (ODFI) and are sent off to other Financial Institutions.  A namespace is a value used to isolate models from each other. This can be set to a \"user ID\" from your authentication service or any value your system has to identify.  There are also [admin endpoints](https://moov-io.github.io/paygate/admin/) for back-office operations.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// Transfer struct for Transfer
type Transfer struct {
	// transferID to uniquely identify this Transfer
	TransferID string `json:"transferID"`
	// Amount of money. USD - United States.
	Amount      string      `json:"amount"`
	Source      Source      `json:"source"`
	Destination Destination `json:"destination"`
	// Brief description of the transaction, that may appear on the receiving entity’s financial statement. This field is put into the Entry Detail's DiscretionaryData.
	Description string         `json:"description"`
	Status      TransferStatus `json:"status"`
	// When set to true this indicates the transfer should be processed the same day if possible.
	SameDay     bool        `json:"sameDay"`
	ReturnCode  *ReturnCode `json:"returnCode,omitempty"`
	ProcessedAt *time.Time  `json:"processedAt,omitempty"`
	Created     time.Time   `json:"created"`
}
