/*
 * Paygate API
 *
 * PayGate is a RESTful API enabling first-party Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transfers to be created without a deep understanding of a full NACHA file specification. First-party transfers initiate at an Originating Depository Financial Institution (ODFI) and are sent off to other Financial Institutions.  Tenants are the largest grouping in PayGate and are typically a vendor who is reselling ACH services or a company making ACH payments themselves. A legal entity is linked off a Tenant as the primary Customer used to KYC and in transfers with the Tenant itself.  An Organization is a grouping within a Tenant which typically represents an entity making ACH transfers. These include clients of an ACH reseller or business accepting payments over ACH. A legal entity is linked off an Organization as the primary Customer used to KYC and in transfers with the Organization itself.  ![](https://raw.githubusercontent.com/moov-io/paygate/master/docs/images/tenant-in-paygate.png)  There are also [admin endpoints](https://moov-io.github.io/paygate/admin/) for back-office operations.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// Transfer struct for Transfer
type Transfer struct {
	// transferID to uniquely identify this Transfer
	TransferID string `json:"transferID"`
	// Amount of money. USD - United States.
	Amount      string      `json:"amount"`
	Source      Source      `json:"source"`
	Destination Destination `json:"destination"`
	// Brief description of the transaction, that may appear on the receiving entity’s financial statement. This field is put into the Entry Detail's DiscretionaryData.
	Description string         `json:"description"`
	Status      TransferStatus `json:"status"`
	// When set to true this indicates the transfer should be processed the same day if possible.
	SameDay     bool       `json:"sameDay"`
	ReturnCode  ReturnCode `json:"returnCode,omitempty"`
	ProcessedAt *time.Time `json:"processedAt,omitempty"`
	Created     time.Time  `json:"created"`
}
